//! User-facing output.
//!
//! Kept in one module so that the shape of pgpushy's output is visible in a
//! single place rather than scattered through the commands. Two conventions,
//! both from spec §G5 and impl-plan §12:
//!
//! - Diagnostics name **every** instance, not the first. A tree with five
//!   unsupported statements prints five.
//! - Anything sourced from the tree names its file and line, and says what to
//!   do about it.
//!
//! Progress and results go to stdout; diagnostics go to stderr, so that
//! `--out`-style piping and error reporting do not interleave.

use crate::config::{Loaded, Settings};
use crate::conn::{PasswordSource, Resolved};
use crate::discovery::Discovered;
use crate::hazard::Hazard;
use crate::inspect::{Identity, PolicyOrRls};
use crate::provider::PgschemaBin;
use pgpushy_core::{Analysis, Diagnostic, Origin, SchemaName, Seeds};
use std::path::Path;

/// What discovery found, before anything is parsed.
///
/// Printed early and unconditionally: when an exclude pattern is too broad, or
/// a source root points somewhere unexpected, the file count is the thing that
/// gives it away.
pub fn discovery(root: &Path, discovered: &Discovered) {
    let total: usize = discovered.excluded.iter().map(|(_, n)| n).sum();
    let plural = if discovered.files.len() == 1 { "" } else { "s" };

    if total == 0 {
        println!(
            "  {} ({} file{plural})",
            root.display(),
            discovered.files.len()
        );
    } else {
        println!(
            "  {} ({} file{plural}, {total} excluded)",
            root.display(),
            discovered.files.len(),
        );
        for (pattern, count) in &discovered.excluded {
            if *count > 0 {
                println!("    excluded by {pattern:?}: {count}");
            }
        }
    }

    if discovered.generated > 0 {
        println!(
            "    skipped {} previously generated by pgpushy",
            discovered.generated,
        );
    }

    if discovered.skipped_seed_root > 0 {
        let n = discovered.skipped_seed_root;
        println!(
            "    excluded {n} seed file{} under the seed root (not desired state)",
            if n == 1 { "" } else { "s" },
        );
    }
}

/// The managed-schema set and what the tree contains.
pub fn summary(settings: &Settings, analysis: &Analysis) {
    let counts = &analysis.counts;
    let mut parts = vec![format!("{} table{}", counts.tables, s(counts.tables))];
    if counts.foreign_keys > 0 {
        parts.push(format!(
            "{} foreign key{}",
            counts.foreign_keys,
            s(counts.foreign_keys)
        ));
    }
    if counts.indexes > 0 {
        parts.push(format!("{} index{}", counts.indexes, es(counts.indexes)));
    }
    if counts.types > 0 {
        parts.push(format!(
            "{} type{} and sequence{}",
            counts.types,
            s(counts.types),
            s(counts.types)
        ));
    }
    if counts.comments > 0 {
        parts.push(format!("{} comment{}", counts.comments, s(counts.comments)));
    }
    println!("  {}", parts.join(", "));

    let declared = if settings.managed_schemas.is_none() {
        ""
    } else {
        " (declared)"
    };
    if !analysis.managed_schemas.is_empty() {
        println!(
            "\n  managed schemas{declared}: {}",
            analysis
                .managed_schemas
                .iter()
                .map(|s| s.as_str().to_owned())
                .collect::<Vec<_>>()
                .join(", "),
        );
    }

    // A managed schema with nothing in it reconciles the target's copy to
    // empty. That is the only way to say so, and it is destructive, so it is
    // never left implicit.
    let empty: Vec<_> = analysis
        .managed_schemas
        .iter()
        .filter(|schema| !mentions(analysis, schema))
        .map(|s| s.as_str())
        .collect();
    if !empty.is_empty() {
        println!(
            "  WARNING: no source file describes {}; applying would plan to drop \
             everything the target holds there",
            empty.join(", "),
        );
    }

    if analysis.counts.seed_files > 0 {
        println!(
            "  {} seed statement{} across {}",
            analysis.counts.seed_statements,
            s(analysis.counts.seed_statements),
            plural(analysis.counts.seed_files, "seed file"),
        );
    }
    // The per-file probe cannot see two files converging against each other
    // (spec §4.6, §12.11), so the statically visible shape is warned about.
    for collision in &analysis.seeds.do_update_collisions {
        println!(
            "  WARNING: two DO UPDATE seeds share a conflict target on {} ({}); \
             each converges alone while together they rewrite the row on every apply",
            collision.table,
            collision
                .origins
                .iter()
                .map(|origin| origin.to_string())
                .collect::<Vec<_>>()
                .join(", "),
        );
    }
}

/// The all-clear, plus the order the schemas would be applied in.
pub fn checks_passed(analysis: &Analysis) {
    println!("\n  ok  no duplicate objects");
    println!("  ok  all foreign key referents resolvable");
    println!("  ok  no cross-schema foreign key cycles");
    println!("  ok  no unsupported statements");
    if analysis.counts.seed_files > 0 {
        println!("  ok  seed statements are idempotent by construction");
    }

    if analysis.order.len() > 1 {
        println!(
            "\n  schema apply order: {}",
            analysis
                .order
                .iter()
                .map(|s| s.as_str().to_owned())
                .collect::<Vec<_>>()
                .join(", "),
        );
    }
}

/// The documents `--out` just wrote (spec §8.7).
pub fn wrote(dir: &Path, written: &[std::path::PathBuf]) {
    println!(
        "\n  wrote {} into {}",
        plural(written.len(), "document"),
        dir.display()
    );
    for path in written {
        if let Some(name) = path.file_name() {
            println!("    {}", name.to_string_lossy());
        }
    }
}

fn plural(n: usize, word: &str) -> String {
    format!("{n} {word}{}", s(n))
}

/// Print every diagnostic, to stderr.
pub fn diagnostics(diagnostics: &[Diagnostic]) {
    eprintln!();
    for diagnostic in diagnostics {
        eprintln!("error: {}", diagnostic.message);
        for origin in &diagnostic.origins {
            eprintln!("  at {origin}");
        }
        if let Some(help) = &diagnostic.help {
            eprintln!("  help: {help}");
        }
        eprintln!();
    }

    let count = diagnostics.len();
    eprintln!("{count} problem{} found in the source tree", s(count));
}

/// Whether any object was assigned to this schema.
fn mentions(analysis: &Analysis, schema: &pgpushy_core::SchemaName) -> bool {
    !analysis.empty_schemas.contains(schema)
}

fn s(n: usize) -> &'static str {
    if n == 1 { "" } else { "s" }
}

fn es(n: usize) -> &'static str {
    if n == 1 { "" } else { "es" }
}

/// Which pgschema is about to be run.
///
/// Printed because the binary in use determines what the plans mean, and a
/// `PATH` lookup can quietly find a different one than the operator expects.
pub fn pgschema(binary: &PgschemaBin) {
    let version = binary
        .version
        .as_ref()
        .map(|v| v.to_string())
        .unwrap_or_else(|| "unknown version".to_owned());
    println!("\n  pgschema {version} ({})", binary.path.display());
}

/// Which database pgpushy actually reached (spec §6.3).
/// Where the comparison model is built, when it is not the embedded default.
///
/// Worth saying: it is a real server that gets written to, and an operator who
/// configured it once should be reminded which one is in play.
pub fn plan_database(connection: &Resolved) {
    if let Some(plan) = &connection.plan_db {
        println!("  plan database: {}", plan.describe());
    }
}

/// Every file discovery kept, under `--verbose`.
pub fn discovered_files(discovered: &Discovered) {
    for file in &discovered.files {
        println!("    {}", file.path);
    }
}

/// The pgschema command line, under `--verbose`.
///
/// Rendered from the built `Command` rather than reassembled, so it is what
/// actually runs. Note the password never appears — it travels through the
/// environment, not the argv (spec §6.3).
pub fn pgschema_command(command: &std::process::Command) {
    let args: Vec<String> = command
        .get_args()
        .map(|arg| arg.to_string_lossy().into_owned())
        .collect();
    println!(
        "  $ {} {}",
        command.get_program().to_string_lossy(),
        args.join(" ")
    );
}

/// Where the synthesized document went, under `--verbose`.
pub fn desired_state_at(path: &Path) {
    println!("  desired state: {}", path.display());
}

/// No managed schemas at all — so there is nothing to reconcile.
///
/// Reported rather than passed over in silence: a run that does nothing looks
/// exactly like a run that reconciled successfully, and the difference matters.
pub fn nothing_managed() {
    println!();
    println!("  No managed schemas — nothing to reconcile.");
    println!("  No source file describes an object, so there is nothing to compare");
    println!("  against the target. pgpushy will not touch anything.");
}

pub fn target(connection: &Resolved, identity: &Identity) {
    // The environment name as well as the database: "prod" and "the database
    // called myapp" are different facts, and a mismatch between them is
    // exactly what an operator wants to catch before approving anything.
    println!("  env {}: {identity}", connection.env);
}

/// Spec §6.1: every managed schema must already exist, and the operator needs
/// all of the missing ones at once rather than one run at a time.
pub fn missing_schemas(missing: &[SchemaName]) {
    eprintln!();
    eprintln!(
        "error: {} managed schema{} missing from the target",
        missing.len(),
        if missing.len() == 1 { " is" } else { "s are" },
    );
    for schema in missing {
        eprintln!("  {schema}");
    }
    eprintln!();
    eprintln!(
        "  help: pgpushy does not create schemas — every change flows through pgschema, \n\
         \x20       which cannot reconcile a schema that does not exist. Create them first:"
    );
    for schema in missing {
        eprintln!("          CREATE SCHEMA {schema};");
    }
}

/// A heading before each per-schema pgschema run, so that pgschema's own
/// output is attributable when several schemas are planned in sequence.
pub fn schema_heading(schema: &SchemaName) {
    println!("\n\u{2500}\u{2500} {schema} \u{2500}\u{2500}");
}

/// Said after a cycle is reported but the plans are shown anyway (spec §7).
pub fn plans_are_diagnostic_only() {
    eprintln!(
        "  the plans below are for diagnosis only; apply cannot run until the cycle is broken"
    );
}

pub fn pgschema_failed(schemas: &[SchemaName]) {
    eprintln!();
    eprintln!(
        "error: pgschema failed for {}",
        schemas
            .iter()
            .map(SchemaName::as_str)
            .collect::<Vec<_>>()
            .join(", "),
    );
}

/// Spec §6.2: a cross-schema removal the apply order cannot satisfy.
///
/// An error in both commands — it makes the change unappliable either way, and
/// `plan` is a gate as much as a preview. `applying` only controls whether the
/// closing line reassures the reader that nothing was touched, which would be
/// a strange thing to say about a command that never applies anything.
pub fn hazards(hazards: &[Hazard], applying: bool) {
    eprintln!();
    eprintln!(
        "error: {} cross-schema foreign key removal{} cannot be applied in one pass",
        hazards.len(),
        s(hazards.len()),
    );

    for hazard in hazards {
        let fk = &hazard.foreign_key;
        eprintln!();
        eprintln!(
            "  {} on {}.{} references {}.{}",
            fk.name, fk.from_schema, fk.from_table, fk.to_schema, fk.to_table,
        );
        eprintln!(
            "  but applying {} would drop the {} it depends on: {}.{}.{}",
            fk.to_schema, hazard.dropped_kind, fk.to_schema, fk.to_table, hazard.dropped,
        );
        eprintln!(
            "  and {} is applied after {}, so the foreign key still exists at that point.",
            fk.from_schema, fk.to_schema,
        );
        eprintln!("  {}", hazard.remedy());
    }

    eprintln!();
    eprintln!("  (dropping the referenced table instead would be fine — pgschema drops");
    eprintln!("   tables with CASCADE, which removes the foreign key along with it.)");
    if applying {
        eprintln!();
        eprintln!("  no schemas were applied.");
    }
}

/// Said when a cycle stops `apply` before anything is planned.
pub fn cycle_blocks_apply() {
    eprintln!("  apply cannot proceed. Run `pgpushy plan` to see the plans for each");
    eprintln!("  schema, which is usually the fastest way to find the constraint to remove.");
    eprintln!();
    eprintln!("  no schemas were applied.");
}

pub fn declined() {
    println!("\n  Aborted. No schemas were applied.");
}

/// A schema whose plan was empty needs no apply at all.
pub fn skipped_unchanged(schema: &SchemaName) {
    println!("\n\u{2500}\u{2500} {schema} \u{2500}\u{2500}");
    println!("No changes; nothing to apply.");
}

pub fn applied(applied: &[SchemaName]) {
    println!();
    if applied.is_empty() {
        println!("  Nothing to apply; the target already matches the source tree.");
    } else {
        println!(
            "  Applied {} schema{}: {}",
            applied.len(),
            s(applied.len()),
            applied
                .iter()
                .map(SchemaName::as_str)
                .collect::<Vec<_>>()
                .join(", "),
        );
    }
}

/// Spec §9: after a failure partway through, say exactly where things stand.
///
/// The three groups are kept separate because they need different responses:
/// what landed, what broke, and what never ran.
pub fn partial_apply(applied: &[SchemaName], failed: &SchemaName, unattempted: &[SchemaName]) {
    eprintln!();
    eprintln!("error: apply failed at schema {failed}");
    eprintln!();

    if applied.is_empty() {
        eprintln!("  applied:      (none)");
    } else {
        eprintln!(
            "  applied:      {}",
            applied
                .iter()
                .map(SchemaName::as_str)
                .collect::<Vec<_>>()
                .join(", "),
        );
    }
    eprintln!("  failed:       {failed}");
    if unattempted.is_empty() {
        eprintln!("  not attempted: (none)");
    } else {
        eprintln!(
            "  not attempted: {}",
            unattempted
                .iter()
                .map(SchemaName::as_str)
                .collect::<Vec<_>>()
                .join(", "),
        );
    }

    if !applied.is_empty() {
        eprintln!();
        eprintln!(
            "  apply is not atomic across schemas: the schemas listed as applied are\n               NOT rolled back. Fix the failure and run pgpushy apply again — the\n               already-applied schemas will plan as no-ops."
        );
    }
}

/// Which configuration file, if any, is in effect.
///
/// Worth a line: `pgpushy.toml` is only read from the working directory, so
/// running from a subdirectory silently picks up nothing, and saying so is
/// cheaper than explaining it later.
pub fn configuration(loaded: &Loaded) {
    println!("  config: {}", loaded.path.display());
}

/// Spec §10: a password read from a file that is easily committed.
///
/// Fires on *use*, not presence — a file password that PGPASSWORD overrode
/// is not a risk worth interrupting anyone about. Made
/// deliberately hard to skim past, because the whole point is that the
/// operator may not know the file has one.
pub fn password_from_file(connection: &Resolved, loaded: &Loaded) {
    if connection.password_source != PasswordSource::File {
        return;
    }
    let path = loaded.path.display();

    eprintln!();
    eprintln!("  \u{26a0} PASSWORD READ FROM {path}");
    eprintln!("    That file is easily committed to version control. Prefer PGPASSWORD");
    eprintln!("    in the environment, and remove it from the file.");
}

/// About to fetch pgschema (spec §8.5).
///
/// Said out loud because pgpushy is downloading and then executing a binary,
/// which the operator should see happening rather than infer from a pause.
pub fn downloading_pgschema(version: &str, platform: &str, unverified: bool) {
    println!("  downloading pgschema {version} ({platform})...");
    if unverified {
        // Spec §8.5 permits pinning a version pgpushy ships no hash for, and
        // requires saying which trust applies.
        println!("    note: pgpushy ships no checksum for {version}, so this download is");
        println!("    trusted on TLS alone. Versions pgpushy pins are checksum-verified.");
    }
}

/// A cached pgschema that no longer matches its shipped checksum.
///
/// Not fatal — the fresh download is verified too — but corruption and
/// tampering are indistinguishable from here, so it is not passed over.
pub fn cache_mismatch(path: &Path) {
    eprintln!();
    eprintln!(
        "warning: the cached pgschema at {} does not match its",
        path.display()
    );
    eprintln!("  expected checksum. Re-downloading. If this repeats, something is");
    eprintln!("  modifying the cache.");
    eprintln!();
}

pub fn downloaded_pgschema(path: &Path) {
    println!("  cached at {}", path.display());
}

// ---------------------------------------------------------------------------
// Seeds (spec §4.6, §8.8)
// ---------------------------------------------------------------------------

/// What seed discovery found, printed beside the source tree's own line.
pub fn seed_discovery(root: &Path, files: usize, generated: usize) {
    println!("  {} ({})", root.display(), plural(files, "seed file"));
    if generated > 0 {
        println!("    skipped {generated} previously generated by pgpushy");
    }
}

/// `plan` lists the seed files and executes none of them (spec §8.8).
pub fn seeds_planned(seeds: &Seeds) {
    println!(
        "\n  {} would be applied after the schemas; plan executes none:",
        plural(seeds.files.len(), "seed file"),
    );
    for file in &seeds.files {
        println!(
            "    {}  {}",
            file.path,
            plural(file.statements.len(), "statement"),
        );
    }
}

pub fn seed_heading(path: &str) {
    println!("\n\u{2500}\u{2500} seed {path} \u{2500}\u{2500}");
}

/// A committed seed file, with its first-pass affected count — the rows that
/// landed or were corrected. The probe pass affected none, by construction.
pub fn seed_applied(path: &str, rows: u64, per_statement: &[(u32, u64)]) {
    println!(
        "  {path}: {rows} row{} affected; probe passed",
        s(usize::try_from(rows).unwrap_or(2)),
    );
    // One statement's count is the file's count; several are worth itemizing
    // (spec §8.8 step 2).
    if per_statement.len() > 1 {
        for (line, count) in per_statement {
            println!(
                "    line {line}: {count} row{}",
                s(usize::try_from(*count).unwrap_or(2)),
            );
        }
    }
}

/// A statement failed outright; the file's transaction rolls back.
pub fn seed_statement_error(path: &str, origin: &Origin, err: &postgres::Error) {
    eprintln!(
        "\nerror: seed {path} failed\n  at {origin}\n  {err}\n\n  The file's \
         transaction was rolled back; nothing from it landed."
    );
}

/// The probe caught a non-convergent seed (spec §8.8, §11.1).
pub fn seed_probe_failure(path: &str, origin: &Origin, affected: u64) {
    eprintln!(
        "\nerror: seed {path} does not converge\n  at {origin}\n  the second pass \
         affected {affected} row{} where it must affect none\n\n  A seed must leave \
         nothing to do when re-run (spec §11.1): a volatile expression, or an update \
         that keeps rewriting rows, cannot be a seed. The file's transaction was \
         rolled back; nothing from it landed.",
        s(usize::try_from(affected).unwrap_or(2)),
    );
}

/// Where the seed pass stopped (spec §9).
pub fn seeds_partial(applied: &[String], failed: &str, unattempted: &[&str]) {
    eprintln!(
        "\n  seed files applied and committed: {}",
        if applied.is_empty() {
            "none".to_owned()
        } else {
            applied.join(", ")
        },
    );
    eprintln!("  failed (rolled back): {failed}");
    if !unattempted.is_empty() {
        eprintln!("  not attempted: {}", unattempted.join(", "));
    }
    eprintln!("\n  Committed seed files are not rolled back (spec §11.2).");
}

/// Schema apply failed, so no seed file ran (spec §9).
pub fn seeds_not_attempted(seeds: &Seeds) {
    eprintln!(
        "\n  {} not attempted: seeds run only after every schema has applied",
        plural(seeds.files.len(), "seed file"),
    );
}

pub fn seeds_done(count: usize) {
    println!("\n  Applied {}.", plural(count, "seed file"));
}

// ---------------------------------------------------------------------------
// Generated sources (spec §4.7)
// ---------------------------------------------------------------------------

pub fn generate_nothing() {
    println!("  no [[generate]] entries configured; nothing to do");
}

pub fn generate_running(command: &[String]) {
    println!("  running: {}", command.join(" "));
}

pub fn generate_wrote(paths: &[std::path::PathBuf]) {
    println!("  wrote {}:", plural(paths.len(), "generated source"));
    for path in paths {
        println!("    {}", path.display());
    }
}

pub fn generate_current(count: usize) {
    println!("  {} current", plural(count, "generated source"));
}

pub fn generate_stale(stale: &[(std::path::PathBuf, &'static str)]) {
    eprintln!(
        "\nerror: {} out of date:",
        plural(stale.len(), "generated source"),
    );
    for (path, why) in stale {
        eprintln!("  {} {why}", path.display());
    }
    eprintln!("\n  Run `pgpushy generate` and commit the result.");
}

// ---------------------------------------------------------------------------
// Untouched kinds (spec §6.5, §8.4) and the plan database (spec §10.4)
// ---------------------------------------------------------------------------

/// Policies and RLS-enabled tables in managed schemas (spec §6.5).
pub fn policies_refused(findings: &[PolicyOrRls], applying: bool) {
    eprintln!(
        "\nerror: managed schemas hold policies or row-level security, which pgpushy \
         can neither manage nor leave alone (spec §6.5):"
    );
    for finding in findings {
        match &finding.policy {
            Some(policy) => {
                eprintln!("  policy {policy} on {}.{}", finding.schema, finding.table);
            }
            None => eprintln!(
                "  row-level security on {}.{}",
                finding.schema, finding.table
            ),
        }
    }
    eprintln!(
        "\n  pgschema\'s ignore file has no section for these, so reconciling the \
         schema would drop the policies and disable the security. Drop them first, \
         or leave the schema out of the managed set."
    );
    if applying {
        eprintln!("\n  apply refuses before touching anything.");
    } else {
        eprintln!("\n  The plans are still computed below; the run exits non-zero.");
    }
}

/// Steps outside pgpushy\'s model (spec §8.4): the enforcement behind the
/// ignore-file suppression.
pub fn unmanaged_steps(violations: &[(SchemaName, crate::plan_file::Step)], applying: bool) {
    let n = violations.len();
    eprintln!(
        "\nerror: {n} plan step{} touch{} something the source tree cannot describe:",
        s(n),
        if n == 1 { "es" } else { "" },
    );
    for (schema, step) in violations {
        eprintln!("  {schema}: {} {} {}", step.operation, step.kind, step.path);
    }
    eprintln!(
        "\n  What the source tree does not describe, pgpushy does not touch \
         (spec §8.4). Seeing this usually means a pgschema release changed its \
         ignore-file sections; please report it to pgpushy."
    );
    if applying {
        eprintln!("\n  apply refuses before touching anything.");
    }
}

/// Leftover state in the plan database (spec §10.4).
pub fn plan_db_leftovers(schemas: &[SchemaName], db: &str) {
    let list = schemas
        .iter()
        .map(|schema| schema.as_str().to_owned())
        .collect::<Vec<_>>()
        .join(", ");
    eprintln!(
        "\nerror: the plan database {db} is not empty: schema{} {list} hold{} objects \
         from a previous run",
        s(schemas.len()),
        if schemas.len() == 1 { "s" } else { "" },
    );
    eprintln!(
        "\n  An external plan database accumulates each run\'s cross-schema closure \
         members, and the next run fails on them midway through the loop \
         (spec §10.4). It is scratch space: drop and recreate it, then re-run.\n\
         \n      DROP DATABASE {db}; CREATE DATABASE {db};"
    );
}
