//! User-facing output.
//!
//! Kept in one module so that the shape of pgpushy's output is visible in a
//! single place rather than scattered through the commands. Two conventions,
//! both from spec §G5 and impl-plan §12:
//!
//! - Diagnostics name **every** instance, not the first. A tree with five
//!   unsupported statements prints five.
//! - Anything sourced from the tree names its file and line, and says what to
//!   do about it.
//!
//! Progress and results go to stdout; diagnostics go to stderr, so that
//! `--out`-style piping and error reporting do not interleave.

use crate::config::{Loaded, Settings};
use crate::conn::{PasswordSource, Resolved};
use crate::discovery::Discovered;
use crate::hazard::Hazard;
use crate::inspect::Identity;
use crate::provider::PgschemaBin;
use pgpushy_core::{Analysis, Diagnostic, SchemaName};
use std::path::Path;

/// What discovery found, before anything is parsed.
///
/// Printed early and unconditionally: when an exclude pattern is too broad, or
/// a source root points somewhere unexpected, the file count is the thing that
/// gives it away.
pub fn discovery(root: &Path, discovered: &Discovered) {
    let total: usize = discovered.excluded.iter().map(|(_, n)| n).sum();
    let plural = if discovered.files.len() == 1 { "" } else { "s" };

    if total == 0 {
        println!(
            "  {} ({} file{plural})",
            root.display(),
            discovered.files.len()
        );
    } else {
        println!(
            "  {} ({} file{plural}, {total} excluded)",
            root.display(),
            discovered.files.len(),
        );
        for (pattern, count) in &discovered.excluded {
            if *count > 0 {
                println!("    excluded by {pattern:?}: {count}");
            }
        }
    }

    if discovered.generated > 0 {
        println!(
            "    skipped {} previously generated by pgpushy",
            discovered.generated,
        );
    }
}

/// The managed-schema set and what the tree contains.
pub fn summary(settings: &Settings, analysis: &Analysis) {
    let counts = &analysis.counts;
    let mut parts = vec![format!("{} table{}", counts.tables, s(counts.tables))];
    if counts.foreign_keys > 0 {
        parts.push(format!(
            "{} foreign key{}",
            counts.foreign_keys,
            s(counts.foreign_keys)
        ));
    }
    if counts.indexes > 0 {
        parts.push(format!("{} index{}", counts.indexes, es(counts.indexes)));
    }
    if counts.constraints > 0 {
        parts.push(format!(
            "{} constraint{}",
            counts.constraints,
            s(counts.constraints)
        ));
    }
    if counts.comments > 0 {
        parts.push(format!("{} comment{}", counts.comments, s(counts.comments)));
    }
    println!("  {}", parts.join(", "));

    let declared = if settings.managed_schemas.is_none() {
        ""
    } else {
        " (declared)"
    };
    println!(
        "\n  managed schemas{declared}: {}",
        analysis
            .managed_schemas
            .iter()
            .map(|s| s.as_str().to_owned())
            .collect::<Vec<_>>()
            .join(", "),
    );

    // A managed schema with nothing in it reconciles the target's copy to
    // empty. That is the only way to say so, and it is destructive, so it is
    // never left implicit.
    let empty: Vec<_> = analysis
        .managed_schemas
        .iter()
        .filter(|schema| !mentions(analysis, schema))
        .map(|s| s.as_str())
        .collect();
    if !empty.is_empty() {
        println!(
            "  WARNING: no source file describes {}; applying would plan to drop \
             everything the target holds there",
            empty.join(", "),
        );
    }
}

/// The all-clear, plus the order the schemas would be applied in.
pub fn checks_passed(analysis: &Analysis) {
    println!("\n  ok  no duplicate objects");
    println!("  ok  all foreign key referents resolvable");
    println!("  ok  no cross-schema foreign key cycles");
    println!("  ok  no unsupported statements");

    if analysis.order.len() > 1 {
        println!(
            "\n  schema apply order: {}",
            analysis
                .order
                .iter()
                .map(|s| s.as_str().to_owned())
                .collect::<Vec<_>>()
                .join(", "),
        );
    }
}

pub fn wrote(path: &Path, contents: &str) {
    let lines = contents.lines().count();
    println!("\n  wrote {} ({lines} lines)", path.display());
}

/// Print every diagnostic, to stderr.
pub fn diagnostics(diagnostics: &[Diagnostic]) {
    eprintln!();
    for diagnostic in diagnostics {
        eprintln!("error: {}", diagnostic.message);
        for origin in &diagnostic.origins {
            eprintln!("  at {origin}");
        }
        if let Some(help) = &diagnostic.help {
            eprintln!("  help: {help}");
        }
        eprintln!();
    }

    let count = diagnostics.len();
    eprintln!("{count} problem{} found in the source tree", s(count));
}

/// Whether any object was assigned to this schema.
///
/// [`Analysis`] reports counts rather than objects, so this is answered from
/// the synthesized document: a schema with objects appears qualifying at least
/// one of them, while a schema with none appears only in its own
/// `CREATE SCHEMA`.
fn mentions(analysis: &Analysis, schema: &pgpushy_core::SchemaName) -> bool {
    analysis.desired_state.contains(&format!("{schema}."))
}

fn s(n: usize) -> &'static str {
    if n == 1 { "" } else { "s" }
}

fn es(n: usize) -> &'static str {
    if n == 1 { "" } else { "es" }
}

/// Which pgschema is about to be run.
///
/// Printed because the binary in use determines what the plans mean, and a
/// `PATH` lookup can quietly find a different one than the operator expects.
pub fn pgschema(binary: &PgschemaBin) {
    let version = binary
        .version
        .as_ref()
        .map(|v| v.to_string())
        .unwrap_or_else(|| "unknown version".to_owned());
    println!("\n  pgschema {version} ({})", binary.path.display());
}

/// Which database pgpushy actually reached (spec §6.3).
pub fn target(connection: &Resolved, identity: &Identity) {
    // The environment name as well as the database: "prod" and "the database
    // called myapp" are different facts, and a mismatch between them is
    // exactly what an operator wants to catch before approving anything.
    println!("  env {}: {identity}", connection.env);
}

/// Spec §6.1: every managed schema must already exist, and the operator needs
/// all of the missing ones at once rather than one run at a time.
pub fn missing_schemas(missing: &[SchemaName]) {
    eprintln!();
    eprintln!(
        "error: {} managed schema{} missing from the target",
        missing.len(),
        if missing.len() == 1 { " is" } else { "s are" },
    );
    for schema in missing {
        eprintln!("  {schema}");
    }
    eprintln!();
    eprintln!(
        "  help: pgpushy does not create schemas — every change flows through pgschema, \n\
         \x20       which cannot reconcile a schema that does not exist. Create them first:"
    );
    for schema in missing {
        eprintln!("          CREATE SCHEMA {schema};");
    }
}

/// A heading before each per-schema pgschema run, so that pgschema's own
/// output is attributable when several schemas are planned in sequence.
pub fn schema_heading(schema: &SchemaName) {
    println!("\n\u{2500}\u{2500} {schema} \u{2500}\u{2500}");
}

/// Said after a cycle is reported but the plans are shown anyway (spec §7).
pub fn plans_are_diagnostic_only() {
    eprintln!(
        "  the plans below are for diagnosis only; apply cannot run until the cycle is broken"
    );
}

pub fn pgschema_failed(schemas: &[SchemaName]) {
    eprintln!();
    eprintln!(
        "error: pgschema failed for {}",
        schemas
            .iter()
            .map(SchemaName::as_str)
            .collect::<Vec<_>>()
            .join(", "),
    );
}

/// Spec §6.2: a cross-schema removal the apply order cannot satisfy.
///
/// An error in both commands — it makes the change unappliable either way, and
/// `plan` is a gate as much as a preview. `applying` only controls whether the
/// closing line reassures the reader that nothing was touched, which would be
/// a strange thing to say about a command that never applies anything.
pub fn hazards(hazards: &[Hazard], applying: bool) {
    eprintln!();
    eprintln!(
        "error: {} cross-schema foreign key removal{} cannot be applied in one pass",
        hazards.len(),
        s(hazards.len()),
    );

    for hazard in hazards {
        let fk = &hazard.foreign_key;
        eprintln!();
        eprintln!(
            "  {} on {}.{} references {}.{}",
            fk.name, fk.from_schema, fk.from_table, fk.to_schema, fk.to_table,
        );
        eprintln!(
            "  but applying {} would drop the {} it depends on: {}.{}.{}",
            fk.to_schema, hazard.dropped_kind, fk.to_schema, fk.to_table, hazard.dropped,
        );
        eprintln!(
            "  and {} is applied after {}, so the foreign key still exists at that point.",
            fk.from_schema, fk.to_schema,
        );
        eprintln!("  {}", hazard.remedy());
    }

    eprintln!();
    eprintln!("  (dropping the referenced table instead would be fine — pgschema drops");
    eprintln!("   tables with CASCADE, which removes the foreign key along with it.)");
    if applying {
        eprintln!();
        eprintln!("  no schemas were applied.");
    }
}

/// Said when a cycle stops `apply` before anything is planned.
pub fn cycle_blocks_apply() {
    eprintln!("  apply cannot proceed. Run `pgpushy plan` to see the plans for each");
    eprintln!("  schema, which is usually the fastest way to find the constraint to remove.");
    eprintln!();
    eprintln!("  no schemas were applied.");
}

pub fn declined() {
    println!("\n  Aborted. No schemas were applied.");
}

/// A schema whose plan was empty needs no apply at all.
pub fn skipped_unchanged(schema: &SchemaName) {
    println!("\n\u{2500}\u{2500} {schema} \u{2500}\u{2500}");
    println!("No changes; nothing to apply.");
}

pub fn applied(applied: &[SchemaName]) {
    println!();
    if applied.is_empty() {
        println!("  Nothing to apply; the target already matches the source tree.");
    } else {
        println!(
            "  Applied {} schema{}: {}",
            applied.len(),
            s(applied.len()),
            applied
                .iter()
                .map(SchemaName::as_str)
                .collect::<Vec<_>>()
                .join(", "),
        );
    }
}

/// Spec §9: after a failure partway through, say exactly where things stand.
///
/// The three groups are kept separate because they need different responses:
/// what landed, what broke, and what never ran.
pub fn partial_apply(applied: &[SchemaName], failed: &SchemaName, unattempted: &[SchemaName]) {
    eprintln!();
    eprintln!("error: apply failed at schema {failed}");
    eprintln!();

    if applied.is_empty() {
        eprintln!("  applied:      (none)");
    } else {
        eprintln!(
            "  applied:      {}",
            applied
                .iter()
                .map(SchemaName::as_str)
                .collect::<Vec<_>>()
                .join(", "),
        );
    }
    eprintln!("  failed:       {failed}");
    if unattempted.is_empty() {
        eprintln!("  not attempted: (none)");
    } else {
        eprintln!(
            "  not attempted: {}",
            unattempted
                .iter()
                .map(SchemaName::as_str)
                .collect::<Vec<_>>()
                .join(", "),
        );
    }

    if !applied.is_empty() {
        eprintln!();
        eprintln!(
            "  apply is not atomic across schemas: the schemas listed as applied are\n               NOT rolled back. Fix the failure and run pgpushy apply again — the\n               already-applied schemas will plan as no-ops."
        );
    }
}

/// Which configuration file, if any, is in effect.
///
/// Worth a line: `pgpushy.toml` is only read from the working directory, so
/// running from a subdirectory silently picks up nothing, and saying so is
/// cheaper than explaining it later.
pub fn configuration(loaded: &Loaded) {
    println!("  config: {}", loaded.path.display());
}

/// Spec §10: a password read from a file that is easily committed.
///
/// Fires on *use*, not presence — a file password that PGPASSWORD or
/// --password overrode is not a risk worth interrupting anyone about. Made
/// deliberately hard to skim past, because the whole point is that the
/// operator may not know the file has one.
pub fn password_from_file(connection: &Resolved, loaded: &Loaded) {
    if connection.password_source != PasswordSource::File {
        return;
    }
    let path = loaded.path.display();

    eprintln!();
    eprintln!("  \u{26a0} PASSWORD READ FROM {path}");
    eprintln!("    That file is easily committed to version control. Prefer PGPASSWORD");
    eprintln!("    in the environment, or --password, and remove it from the file.");
}
