//! End-to-end tests for the offline pipeline.
//!
//! `pgpushy-core` takes `(path, contents)` pairs rather than reading the
//! filesystem, so every one of these is a string-literal test with no fixture
//! directory to keep in sync — which is the main reason discovery lives in the
//! binary and everything downstream of it does not.

use pgpushy_core::{
    Analysis, AnalysisError, Diagnostic, DiagnosticKind, Options, SchemaName, SourceFile, analyze,
};

fn file(path: &str, contents: &str) -> SourceFile {
    SourceFile {
        path: path.to_owned(),
        contents: contents.to_owned(),
    }
}

fn analyze_with(files: &[SourceFile], options: &Options) -> Result<Analysis, AnalysisError> {
    analyze(files, options)
}

fn ok(files: Vec<SourceFile>) -> Analysis {
    ok_with(files, &Options::default())
}

fn ok_with(files: Vec<SourceFile>, options: &Options) -> Analysis {
    match analyze_with(&files, options) {
        Ok(analysis) => analysis,
        Err(err) => panic!("expected success, got:\n{}", render(&err)),
    }
}

fn err(files: Vec<SourceFile>) -> Vec<Diagnostic> {
    err_with(files, &Options::default())
}

fn err_with(files: Vec<SourceFile>, options: &Options) -> Vec<Diagnostic> {
    match analyze_with(&files, options) {
        Ok(_) => panic!("expected failure, got success"),
        Err(AnalysisError::Source(diagnostics)) => diagnostics,
        Err(other) => panic!("expected source diagnostics, got: {other}"),
    }
}

fn render(err: &AnalysisError) -> String {
    match err {
        AnalysisError::Source(diagnostics) => diagnostics
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n"),
        other => other.to_string(),
    }
}

fn only(diagnostics: &[Diagnostic], kind: DiagnosticKind) -> &Diagnostic {
    assert_eq!(
        diagnostics.iter().map(|d| d.kind).collect::<Vec<_>>(),
        vec![kind],
        "unexpected diagnostics:\n{}",
        diagnostics
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n"),
    );
    &diagnostics[0]
}

fn schema(name: &str) -> SchemaName {
    SchemaName::new(name)
}

fn schemas(names: &[&str]) -> Vec<SchemaName> {
    names.iter().map(|n| schema(n)).collect()
}

/// The body of a synthesized document, minus the fixed header.
fn body(analysis: &Analysis) -> String {
    analysis
        .desired_state
        .lines()
        .skip_while(|line| line.starts_with("--") || line.is_empty())
        .collect::<Vec<_>>()
        .join("\n")
}

// ---------------------------------------------------------------------------
// Synthesis
// ---------------------------------------------------------------------------

/// The whole point, in one test: files in any order, foreign keys inline,
/// nothing qualified — and out comes a document that executes top to bottom.
#[test]
fn synthesizes_an_order_free_source_tree() {
    let analysis = ok(vec![
        // Deliberately the "wrong" order: the child table first, referencing a
        // parent defined in a file that sorts later. Raw pgschema fails on
        // this; pgpushy must not.
        file(
            "b_orders.sql",
            "CREATE TABLE orders (id int PRIMARY KEY, customer_id int NOT NULL REFERENCES customers(id));",
        ),
        file(
            "a_customers.sql",
            "CREATE TABLE customers (id int PRIMARY KEY, name text NOT NULL);",
        ),
    ]);

    assert_eq!(analysis.managed_schemas, schemas(&["public"]));
    assert_eq!(analysis.counts.tables, 2);
    assert_eq!(analysis.counts.foreign_keys, 1);
    assert!(analysis.cycles.is_empty());

    assert_eq!(
        analysis.desired_state,
        "-- Generated by pgpushy. Do not edit.\n\
         --\n\
         -- This is the desired state pgschema diffs against the target: every\n\
         -- managed schema's objects, schema-qualified, with foreign keys lifted\n\
         -- out of their tables so that no ordering among tables can matter.\n\
         \n\
         -- schemas\n\
         CREATE SCHEMA IF NOT EXISTS public;\n\
         \n\
         -- tables\n\
         CREATE TABLE public.customers (id int PRIMARY KEY, name text NOT NULL);\n\
         CREATE TABLE public.orders (id int PRIMARY KEY, customer_id int NOT NULL);\n\
         \n\
         -- foreign keys\n\
         ALTER TABLE public.orders ADD FOREIGN KEY (customer_id) REFERENCES public.customers (id);\n",
    );
}

/// Every category, in order, with each kind of statement the allow-list admits.
#[test]
fn emits_every_category_in_order() {
    let analysis = ok(vec![file(
        "all.sql",
        r#"
        COMMENT ON TABLE orders IS 'one per purchase';
        ALTER TABLE orders ADD CONSTRAINT orders_total_positive CHECK (total > 0);
        CREATE INDEX orders_customer_idx ON orders (customer_id);
        CREATE TABLE orders (id int PRIMARY KEY, customer_id int, total numeric);
        CREATE TABLE customers (id int PRIMARY KEY);
        ALTER TABLE orders ADD CONSTRAINT orders_customer_fk
            FOREIGN KEY (customer_id) REFERENCES customers(id);
        "#,
    )]);

    assert_eq!(
        body(&analysis),
        "CREATE SCHEMA IF NOT EXISTS public;\n\
         \n\
         -- tables\n\
         CREATE TABLE public.customers (id int PRIMARY KEY);\n\
         CREATE TABLE public.orders (id int PRIMARY KEY, customer_id int, total numeric);\n\
         \n\
         -- indexes and table constraints\n\
         CREATE INDEX orders_customer_idx ON public.orders USING btree (customer_id);\n\
         ALTER TABLE public.orders ADD CONSTRAINT orders_total_positive CHECK (total > 0);\n\
         \n\
         -- foreign keys\n\
         ALTER TABLE public.orders ADD CONSTRAINT orders_customer_fk FOREIGN KEY (customer_id) REFERENCES public.customers (id);\n\
         \n\
         -- comments\n\
         COMMENT ON TABLE public.orders IS 'one per purchase';",
    );
}

/// Spec §5.3: a foreign key the author did not name is emitted with no name,
/// so Postgres generates the same one it already generated on the target. A
/// name the author *did* write survives untouched.
#[test]
fn preserves_author_constraint_names_and_omits_generated_ones() {
    let analysis = ok(vec![file(
        "t.sql",
        "CREATE TABLE parent (id int PRIMARY KEY);
         CREATE TABLE a (pid int REFERENCES parent(id));
         CREATE TABLE b (pid int CONSTRAINT b_parent_fk REFERENCES parent(id));",
    )]);

    assert!(
        analysis
            .desired_state
            .contains("ALTER TABLE public.a ADD FOREIGN KEY (pid) REFERENCES public.parent (id);"),
        "unnamed constraint should stay unnamed:\n{}",
        analysis.desired_state
    );
    assert!(
        analysis.desired_state.contains(
            "ALTER TABLE public.b ADD CONSTRAINT b_parent_fk FOREIGN KEY (pid) REFERENCES public.parent (id);"
        ),
        "author's name should survive:\n{}",
        analysis.desired_state
    );
}

/// Spec §5.4: every identifier is qualified, including in the default schema,
/// because the combined document is run once per schema and an unqualified
/// object would be claimed by all of them.
#[test]
fn qualifies_every_identifier_including_the_default_schema() {
    let analysis = ok(vec![file(
        "t.sql",
        "CREATE SCHEMA billing;
         CREATE TABLE customers (id int PRIMARY KEY);
         CREATE TABLE billing.invoices (id int PRIMARY KEY, customer_id int REFERENCES customers(id));
         CREATE INDEX invoices_customer_idx ON billing.invoices (customer_id);",
    )]);

    for expected in [
        "CREATE TABLE public.customers",
        "CREATE TABLE billing.invoices",
        "ON billing.invoices",
        "REFERENCES public.customers",
    ] {
        assert!(
            analysis.desired_state.contains(expected),
            "expected {expected:?} in:\n{}",
            analysis.desired_state
        );
    }
}

/// A same-schema cycle has no valid inline ordering at all, which is the case
/// FK-lift exists for. It must produce no cross-schema edge and no complaint;
/// pgschema defers one constraint itself.
#[test]
fn same_schema_cycles_are_fine() {
    let analysis = ok(vec![file(
        "spouses.sql",
        "CREATE TABLE husband (id int PRIMARY KEY, wife_id int REFERENCES wife(id));
         CREATE TABLE wife (id int PRIMARY KEY, husband_id int REFERENCES husband(id));",
    )]);

    assert!(analysis.cycles.is_empty());
    assert_eq!(analysis.order, schemas(&["public"]));
    assert_eq!(analysis.counts.foreign_keys, 2);
}

// ---------------------------------------------------------------------------
// Determinism (spec §11.3)
// ---------------------------------------------------------------------------

#[test]
fn output_does_not_depend_on_file_order() {
    let contents = [
        (
            "z.sql",
            "CREATE TABLE zebra (id int PRIMARY KEY, a_id int REFERENCES aardvark(id));",
        ),
        ("a.sql", "CREATE TABLE aardvark (id int PRIMARY KEY);"),
        (
            "m.sql",
            "CREATE TABLE mongoose (id int PRIMARY KEY, z_id int REFERENCES zebra(id));",
        ),
    ];

    let forward = ok(contents.iter().map(|(p, c)| file(p, c)).collect());
    let reversed = ok(contents.iter().rev().map(|(p, c)| file(p, c)).collect());

    assert_eq!(forward.desired_state, reversed.desired_state);
    assert_eq!(forward.order, reversed.order);
}

#[test]
fn repeated_analysis_is_byte_identical() {
    let files = || {
        vec![file(
            "t.sql",
            "CREATE SCHEMA billing;
             CREATE TABLE billing.invoices (id int PRIMARY KEY, c int REFERENCES customers(id));
             CREATE TABLE customers (id int PRIMARY KEY);
             CREATE INDEX i ON customers (id);
             COMMENT ON TABLE customers IS 'people';",
        )]
    };

    assert_eq!(ok(files()).desired_state, ok(files()).desired_state);
}

// ---------------------------------------------------------------------------
// The statement allow-list (spec §4.3)
// ---------------------------------------------------------------------------

#[test]
fn rejects_statements_outside_the_allow_list() {
    for (sql, expected) in [
        ("CREATE VIEW v AS SELECT 1;", "CREATE VIEW"),
        ("INSERT INTO t VALUES (1);", "INSERT"),
        ("DROP TABLE t;", "DROP"),
        ("GRANT SELECT ON t TO joe;", "GRANT or REVOKE"),
        ("CREATE TYPE mood AS ENUM ('ok');", "CREATE TYPE"),
        ("CREATE SEQUENCE s;", "CREATE SEQUENCE"),
        ("ALTER TABLE t ADD COLUMN c int;", "ADD CONSTRAINT"),
        ("CREATE TABLE t (id int) INHERITS (parent);", "INHERITS"),
        ("CREATE INDEX CONCURRENTLY i ON t (c);", "CONCURRENTLY"),
    ] {
        let diagnostics = err(vec![file("bad.sql", sql)]);
        let diagnostic = only(&diagnostics, DiagnosticKind::UnsupportedStatement);
        assert!(
            diagnostic.message.contains(expected)
                || diagnostic
                    .help
                    .as_deref()
                    .is_some_and(|h| h.contains(expected)),
            "{sql:?} should mention {expected:?}, got: {diagnostic}",
        );
        assert_eq!(diagnostic.origins.len(), 1);
        assert_eq!(diagnostic.origins[0].file, "bad.sql");
    }
}

#[test]
fn reports_every_unsupported_statement_not_just_the_first() {
    let diagnostics = err(vec![
        file("a.sql", "CREATE VIEW v AS SELECT 1;"),
        file("b.sql", "INSERT INTO t VALUES (1);"),
        file("c.sql", "CREATE TABLE ok (id int);"),
    ]);

    assert_eq!(diagnostics.len(), 2);
    assert_eq!(
        diagnostics
            .iter()
            .map(|d| d.origins[0].file.as_str())
            .collect::<Vec<_>>(),
        vec!["a.sql", "b.sql"],
    );
}

#[test]
fn reports_the_line_a_bad_statement_is_on() {
    let diagnostics = err(vec![file(
        "multi.sql",
        "CREATE TABLE a (id int);\n\
         CREATE TABLE b (id int);\n\
         CREATE VIEW v AS SELECT 1;\n",
    )]);

    let diagnostic = only(&diagnostics, DiagnosticKind::UnsupportedStatement);
    assert_eq!(diagnostic.origins[0].line, 3);
}

#[test]
fn rejects_create_schema_forms_it_cannot_model() {
    for sql in [
        "CREATE SCHEMA billing CREATE TABLE accounts (id int);",
        "CREATE SCHEMA AUTHORIZATION joe;",
        "CREATE SCHEMA billing AUTHORIZATION joe;",
    ] {
        let diagnostics = err(vec![file("s.sql", sql)]);
        only(&diagnostics, DiagnosticKind::UnsupportedSchemaForm);
    }
}

#[test]
fn accepts_the_bare_create_schema_form() {
    let analysis = ok(vec![file(
        "s.sql",
        "CREATE SCHEMA billing;
         CREATE SCHEMA IF NOT EXISTS analytics;",
    )]);
    assert_eq!(analysis.managed_schemas, schemas(&["analytics", "billing"]));
}

#[test]
fn reports_a_parse_failure_with_the_file() {
    let diagnostics = err(vec![file("broken.sql", "CREATE TABLE (((;")]);
    let diagnostic = only(&diagnostics, DiagnosticKind::ParseFailure);
    assert_eq!(diagnostic.origins[0].file, "broken.sql");
}

// ---------------------------------------------------------------------------
// Source-tree validity (spec §4.5, §12.4)
// ---------------------------------------------------------------------------

#[test]
fn rejects_a_duplicate_object_naming_both_definitions() {
    let diagnostics = err(vec![
        file(
            "services/a/orders.sql",
            "CREATE TABLE orders (id int PRIMARY KEY);",
        ),
        file(
            "services/b/orders.sql",
            "CREATE TABLE orders (id int PRIMARY KEY);",
        ),
    ]);

    let diagnostic = only(&diagnostics, DiagnosticKind::DuplicateObject);
    assert!(
        diagnostic.message.contains("table public.orders"),
        "{diagnostic}"
    );
    assert_eq!(
        diagnostic
            .origins
            .iter()
            .map(|o| o.file.as_str())
            .collect::<Vec<_>>(),
        vec!["services/a/orders.sql", "services/b/orders.sql"],
        "both definitions must be named",
    );
}

#[test]
fn rejects_a_foreign_key_to_a_table_no_file_defines() {
    let diagnostics = err(vec![file(
        "orders.sql",
        "CREATE TABLE orders (id int PRIMARY KEY, customer_id int REFERENCES customers(id));",
    )]);

    let diagnostic = only(&diagnostics, DiagnosticKind::UnresolvedReference);
    assert!(
        diagnostic.message.contains("public.customers"),
        "{diagnostic}"
    );
}

/// A foreign key into a schema the tree does not describe is the common cause,
/// and the help should say so rather than implying a missing file.
#[test]
fn explains_a_foreign_key_into_an_unmanaged_schema() {
    let diagnostics = err(vec![file(
        "orders.sql",
        "CREATE TABLE orders (id int PRIMARY KEY, user_id int REFERENCES auth.users(id));",
    )]);

    let diagnostic = only(&diagnostics, DiagnosticKind::UnresolvedReference);
    let help = diagnostic.help.as_deref().unwrap_or_default();
    assert!(
        help.contains("auth"),
        "help should name the schema: {diagnostic}"
    );
}

/// Spec §12.4: verified against Postgres 18, the numeric suffix Postgres adds
/// when two constraints compete for a name follows creation order — so these
/// two could swap names between the target and pgpushy's emission order.
#[test]
fn rejects_unnamed_foreign_keys_that_would_compete_for_one_name() {
    let diagnostics = err(vec![file(
        "dual.sql",
        "CREATE TABLE t1 (id int PRIMARY KEY);
         CREATE TABLE t2 (id int PRIMARY KEY);
         CREATE TABLE dual (ref_id int REFERENCES t1(id));
         ALTER TABLE dual ADD FOREIGN KEY (ref_id) REFERENCES t2(id);",
    )]);

    let diagnostic = only(&diagnostics, DiagnosticKind::CollidingUnnamedForeignKeys);
    assert!(
        diagnostic.message.contains("public.dual(ref_id)"),
        "{diagnostic}"
    );
    assert_eq!(diagnostic.origins.len(), 2);
}

/// The check is exact: naming either constraint resolves it, and two unnamed
/// foreign keys over *different* columns never collide.
#[test]
fn allows_unnamed_foreign_keys_that_cannot_collide() {
    ok(vec![file(
        "fine.sql",
        "CREATE TABLE t1 (id int PRIMARY KEY);
         CREATE TABLE t2 (id int PRIMARY KEY);
         -- different columns: different generated names
         CREATE TABLE a (x int REFERENCES t1(id), y int REFERENCES t2(id));
         -- same column, but one is named
         CREATE TABLE b (z int REFERENCES t1(id));
         ALTER TABLE b ADD CONSTRAINT b_z_t2_fk FOREIGN KEY (z) REFERENCES t2(id);",
    )]);
}

// ---------------------------------------------------------------------------
// The managed-schema set (spec §4.4)
// ---------------------------------------------------------------------------

/// The rule that keeps pgpushy from emptying a schema it was never told about:
/// a schema with no objects is not managed, even when it is the default.
#[test]
fn the_default_schema_is_not_managed_unless_it_holds_something() {
    let analysis = ok(vec![file(
        "billing.sql",
        "CREATE SCHEMA billing; CREATE TABLE billing.invoices (id int PRIMARY KEY);",
    )]);

    assert_eq!(analysis.managed_schemas, schemas(&["billing"]));
}

#[test]
fn a_declaration_rejects_a_schema_it_omits() {
    let options = Options {
        managed_schemas: Some(schemas(&["public"])),
        ..Options::default()
    };
    let diagnostics = err_with(
        vec![
            file("public.sql", "CREATE TABLE customers (id int PRIMARY KEY);"),
            file(
                "reporting/events.sql",
                "CREATE TABLE analytics.events (id int PRIMARY KEY);",
            ),
        ],
        &options,
    );

    let diagnostic = only(&diagnostics, DiagnosticKind::SchemaNotManaged);
    assert!(diagnostic.message.contains("analytics"), "{diagnostic}");
    assert_eq!(
        diagnostic.origins[0].file, "reporting/events.sql",
        "the diagnostic must name the file that enlisted the schema",
    );
}

/// A declared schema the tree never mentions is managed with an empty desired
/// state — the only way to say "reconcile this to empty", and destructive on
/// purpose.
#[test]
fn a_declaration_can_manage_a_schema_the_tree_never_mentions() {
    let options = Options {
        managed_schemas: Some(schemas(&["public", "legacy"])),
        ..Options::default()
    };
    let analysis = ok_with(
        vec![file(
            "t.sql",
            "CREATE TABLE customers (id int PRIMARY KEY);",
        )],
        &options,
    );

    assert_eq!(analysis.managed_schemas, schemas(&["legacy", "public"]));
    assert!(
        analysis
            .desired_state
            .contains("CREATE SCHEMA IF NOT EXISTS legacy;")
    );
}

#[test]
fn a_non_default_default_schema_assigns_unqualified_objects() {
    let options = Options {
        default_schema: schema("app"),
        ..Options::default()
    };
    let analysis = ok_with(
        vec![file(
            "t.sql",
            "CREATE TABLE customers (id int PRIMARY KEY);",
        )],
        &options,
    );

    assert_eq!(analysis.managed_schemas, schemas(&["app"]));
    assert!(
        analysis
            .desired_state
            .contains("CREATE TABLE app.customers")
    );
}

// ---------------------------------------------------------------------------
// Cross-schema ordering (spec §7)
// ---------------------------------------------------------------------------

#[test]
fn orders_referenced_schemas_first() {
    let analysis = ok(vec![file(
        "t.sql",
        "CREATE SCHEMA billing;
         CREATE SCHEMA reporting;
         CREATE TABLE customers (id int PRIMARY KEY);
         CREATE TABLE billing.invoices (id int PRIMARY KEY, c int REFERENCES customers(id));
         CREATE TABLE reporting.summaries (id int PRIMARY KEY, i int REFERENCES billing.invoices(id));",
    )]);

    assert!(analysis.cycles.is_empty());
    assert_eq!(analysis.order, schemas(&["public", "billing", "reporting"]));
}

/// Schemas with no cross-schema foreign keys still appear, in a stable order.
#[test]
fn independent_schemas_are_ordered_by_name() {
    let analysis = ok(vec![file(
        "t.sql",
        "CREATE SCHEMA b; CREATE SCHEMA a; CREATE SCHEMA c;
         CREATE TABLE a.t (id int); CREATE TABLE b.t (id int); CREATE TABLE c.t (id int);",
    )]);

    assert_eq!(analysis.order, schemas(&["a", "b", "c"]));
}

/// A cycle is returned as data, not an error: `plan` shows the plans anyway,
/// because those plans are what the operator needs to break it.
#[test]
fn detects_a_cross_schema_cycle_without_failing_analysis() {
    let analysis = ok(vec![file(
        "t.sql",
        "CREATE SCHEMA billing;
         CREATE TABLE customers (id int PRIMARY KEY, account_id int REFERENCES billing.accounts(id));
         CREATE TABLE billing.accounts (id int PRIMARY KEY, owner_id int REFERENCES customers(id));",
    )]);

    assert_eq!(analysis.cycles.len(), 1);
    assert_eq!(analysis.cycles[0].schemas, schemas(&["billing", "public"]));
    assert_eq!(
        analysis.order.len(),
        2,
        "every schema still appears in the order"
    );

    let diagnostic = &analysis.cycle_diagnostics()[0];
    assert_eq!(diagnostic.kind, DiagnosticKind::CrossSchemaForeignKeyCycle);
    assert!(diagnostic.message.contains("billing"), "{diagnostic}");
    assert!(diagnostic.message.contains("public"), "{diagnostic}");
    assert_eq!(
        diagnostic.origins.len(),
        2,
        "both constraints should be named"
    );
}

#[test]
fn a_three_schema_cycle_names_all_three() {
    let analysis = ok(vec![file(
        "t.sql",
        "CREATE SCHEMA b; CREATE SCHEMA c;
         CREATE TABLE a (id int PRIMARY KEY, r int REFERENCES b.b(id));
         CREATE TABLE b.b (id int PRIMARY KEY, r int REFERENCES c.c(id));
         CREATE TABLE c.c (id int PRIMARY KEY, r int REFERENCES a(id));",
    )]);

    assert_eq!(analysis.cycles.len(), 1);
    assert_eq!(analysis.cycles[0].schemas, schemas(&["b", "c", "public"]));
}
