//! End-to-end tests for the offline pipeline.
//!
//! `pgpushy-core` takes `(path, contents)` pairs rather than reading the
//! filesystem, so every one of these is a string-literal test with no fixture
//! directory to keep in sync — which is the main reason discovery lives in the
//! binary and everything downstream of it does not.

use pgpushy_core::{
    Analysis, AnalysisError, Diagnostic, DiagnosticKind, Options, SchemaName, SourceFile, analyze,
};

fn file(path: &str, contents: &str) -> SourceFile {
    SourceFile {
        path: path.to_owned(),
        contents: contents.to_owned(),
    }
}

fn analyze_with(files: &[SourceFile], options: &Options) -> Result<Analysis, AnalysisError> {
    analyze(files, options)
}

fn ok(files: Vec<SourceFile>) -> Analysis {
    ok_with(files, &Options::default())
}

fn ok_with(files: Vec<SourceFile>, options: &Options) -> Analysis {
    match analyze_with(&files, options) {
        Ok(analysis) => analysis,
        Err(err) => panic!("expected success, got:\n{}", render(&err)),
    }
}

fn err(files: Vec<SourceFile>) -> Vec<Diagnostic> {
    err_with(files, &Options::default())
}

fn err_with(files: Vec<SourceFile>, options: &Options) -> Vec<Diagnostic> {
    match analyze_with(&files, options) {
        Ok(_) => panic!("expected failure, got success"),
        Err(AnalysisError::Source(diagnostics)) => diagnostics,
        Err(other) => panic!("expected source diagnostics, got: {other}"),
    }
}

fn render(err: &AnalysisError) -> String {
    match err {
        AnalysisError::Source(diagnostics) => diagnostics
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n"),
        other => other.to_string(),
    }
}

fn only(diagnostics: &[Diagnostic], kind: DiagnosticKind) -> &Diagnostic {
    assert_eq!(
        diagnostics.iter().map(|d| d.kind).collect::<Vec<_>>(),
        vec![kind],
        "unexpected diagnostics:\n{}",
        diagnostics
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join("\n"),
    );
    &diagnostics[0]
}

fn schema(name: &str) -> SchemaName {
    SchemaName::new(name)
}

fn schemas(names: &[&str]) -> Vec<SchemaName> {
    names.iter().map(|n| schema(n)).collect()
}

/// The body of the `public` document, minus the fixed header.
fn body(analysis: &Analysis) -> String {
    document(analysis, "public")
}

/// The body of one schema's document, minus the fixed header.
fn document(analysis: &Analysis, schema: &str) -> String {
    analysis
        .documents
        .get(&SchemaName::new(schema))
        .unwrap_or_else(|| {
            panic!(
                "no document for {schema}; have {:?}",
                analysis.documents.keys().collect::<Vec<_>>()
            )
        })
        .lines()
        .skip_while(|line| line.starts_with("--") || line.is_empty())
        .collect::<Vec<_>>()
        .join("\n")
}

// ---------------------------------------------------------------------------
// Synthesis
// ---------------------------------------------------------------------------

/// The whole point, in one test: files in any order, foreign keys inline,
/// nothing qualified — and out comes a document that executes top to bottom.
#[test]
fn synthesizes_an_order_free_source_tree() {
    let analysis = ok(vec![
        // Deliberately the "wrong" order: the child table first, referencing a
        // parent defined in a file that sorts later. Raw pgschema fails on
        // this; pgpushy must not.
        file(
            "b_orders.sql",
            "CREATE TABLE orders (id int PRIMARY KEY, customer_id int NOT NULL REFERENCES customers(id));",
        ),
        file(
            "a_customers.sql",
            "CREATE TABLE customers (id int PRIMARY KEY, name text NOT NULL);",
        ),
    ]);

    assert_eq!(analysis.managed_schemas, schemas(&["public"]));
    assert_eq!(analysis.counts.tables, 2);
    assert_eq!(analysis.counts.foreign_keys, 1);
    assert!(analysis.cycles.is_empty());

    assert_eq!(
        analysis.documents[&SchemaName::new("public")],
        "-- Generated by pgpushy. Do not edit.\n\
         --\n\
         -- The desired state of schema public, as pgschema diffs it against the\n\
         -- target. Objects from other schemas appear only so that references\n\
         -- into them resolve; pgschema does not compare them.\n\
         \n\
         -- schemas\n\
         CREATE SCHEMA IF NOT EXISTS public;\n\
         \n\
         -- tables\n\
         CREATE TABLE public.customers (id int PRIMARY KEY, name text NOT NULL);\n\
         CREATE TABLE public.orders (id int PRIMARY KEY, customer_id int NOT NULL);\n\
         \n\
         -- foreign keys\n\
         ALTER TABLE public.orders ADD FOREIGN KEY (customer_id) REFERENCES public.customers (id);\n",
    );
}

/// Every category, in order, with each kind of statement the allow-list admits.
#[test]
fn emits_every_category_in_order() {
    let analysis = ok(vec![file(
        "all.sql",
        r#"
        COMMENT ON TABLE orders IS 'one per purchase';
        CREATE INDEX orders_customer_idx ON orders (customer_id);
        CREATE TABLE orders (
            id int PRIMARY KEY,
            customer_id int,
            total numeric,
            CONSTRAINT orders_total_positive CHECK (total > 0)
        );
        CREATE TABLE customers (id int PRIMARY KEY);
        ALTER TABLE orders ADD CONSTRAINT orders_customer_fk
            FOREIGN KEY (customer_id) REFERENCES customers(id);
        "#,
    )]);

    assert_eq!(
        body(&analysis),
        "CREATE SCHEMA IF NOT EXISTS public;\n\
         \n\
         -- tables\n\
         CREATE TABLE public.customers (id int PRIMARY KEY);\n\
         CREATE TABLE public.orders (id int PRIMARY KEY, customer_id int, total numeric, CONSTRAINT orders_total_positive CHECK (total > 0));\n\
         \n\
         -- indexes\n\
         CREATE INDEX orders_customer_idx ON public.orders USING btree (customer_id);\n\
         \n\
         -- foreign keys\n\
         ALTER TABLE public.orders ADD CONSTRAINT orders_customer_fk FOREIGN KEY (customer_id) REFERENCES public.customers (id);\n\
         \n\
         -- comments\n\
         COMMENT ON TABLE public.orders IS 'one per purchase';",
    );
}

/// Spec §4.3: `ALTER` describes a step, not a state. A foreign key added this
/// way is the single exception, because it is pgpushy's own output shape.
#[test]
fn rejects_standalone_non_foreign_key_constraints() {
    for (what, sql) in [
        ("CHECK", "ALTER TABLE t ADD CONSTRAINT c CHECK (a > 0);"),
        ("UNIQUE", "ALTER TABLE t ADD CONSTRAINT c UNIQUE (a);"),
        (
            "PRIMARY KEY",
            "ALTER TABLE t ADD CONSTRAINT c PRIMARY KEY (a);",
        ),
        (
            "UNIQUE",
            "ALTER TABLE t ADD CONSTRAINT c UNIQUE USING INDEX i;",
        ),
    ] {
        let source = format!("CREATE TABLE t (a int);\n{sql}\n");
        let diagnostics = err(vec![file("t.sql", &source)]);
        let diagnostic = only(&diagnostics, DiagnosticKind::UnsupportedStatement);
        let rendered = diagnostic.to_string();
        assert!(
            rendered.contains(what),
            "{sql}\nshould name the constraint kind, got:\n{rendered}"
        );
        assert!(
            rendered.contains("CREATE TABLE public.t"),
            "{sql}\nshould say where to write it instead, got:\n{rendered}"
        );
    }
}

/// The foreign-key form stays, whether or not the author named it.
#[test]
fn keeps_standalone_foreign_key_constraints() {
    let analysis = ok(vec![file(
        "t.sql",
        "CREATE TABLE parent (id int PRIMARY KEY);\n\
         CREATE TABLE child (pid int);\n\
         ALTER TABLE child ADD FOREIGN KEY (pid) REFERENCES parent(id);\n",
    )]);
    assert!(body(&analysis).contains("ALTER TABLE public.child ADD FOREIGN KEY"));
}

/// Spec §4.3: `LIKE` is the same table-to-table creation dependency as
/// `INHERITS`, hidden inside the column list instead of in a clause.
#[test]
fn rejects_create_table_like() {
    let diagnostics = err(vec![file(
        "t.sql",
        "CREATE TABLE zebra (id int PRIMARY KEY);\n\
         CREATE TABLE alpha (LIKE zebra INCLUDING ALL);\n",
    )]);
    let diagnostic = only(&diagnostics, DiagnosticKind::UnsupportedStatement);
    assert!(
        diagnostic.to_string().contains("LIKE"),
        "got:\n{diagnostic}"
    );
}

/// Spec §5.3: a foreign key the author did not name is emitted with no name,
/// so Postgres generates the same one it already generated on the target. A
/// name the author *did* write survives untouched.
#[test]
fn preserves_author_constraint_names_and_omits_generated_ones() {
    let analysis = ok(vec![file(
        "t.sql",
        "CREATE TABLE parent (id int PRIMARY KEY);
         CREATE TABLE a (pid int REFERENCES parent(id));
         CREATE TABLE b (pid int CONSTRAINT b_parent_fk REFERENCES parent(id));",
    )]);

    let public = document(&analysis, "public");
    assert!(
        public
            .contains("ALTER TABLE public.a ADD FOREIGN KEY (pid) REFERENCES public.parent (id);"),
        "unnamed constraint should stay unnamed:\n{public}"
    );
    assert!(
        public.contains(
            "ALTER TABLE public.b ADD CONSTRAINT b_parent_fk FOREIGN KEY (pid) REFERENCES public.parent (id);"
        ),
        "author's name should survive:\n{public}"
    );
}

/// Spec §5.4: every identifier is qualified, including in the default schema,
/// because an unqualified object is claimed by whichever schema's run reads it.
#[test]
fn qualifies_every_identifier_including_the_default_schema() {
    let analysis = ok(vec![file(
        "t.sql",
        "CREATE SCHEMA billing;
         CREATE TABLE customers (id int PRIMARY KEY);
         CREATE TABLE billing.invoices (id int PRIMARY KEY, customer_id int REFERENCES customers(id));
         CREATE INDEX invoices_customer_idx ON billing.invoices (customer_id);",
    )]);

    // `billing` references `public`, so `public.customers` is a closure member
    // of billing's document and both are qualified there (spec §5.4).
    let billing = document(&analysis, "billing");
    for expected in [
        "CREATE TABLE public.customers",
        "CREATE TABLE billing.invoices",
        "ON billing.invoices",
        "REFERENCES public.customers",
    ] {
        assert!(
            billing.contains(expected),
            "expected {expected:?} in billing's document:\n{billing}"
        );
    }
}

/// A same-schema cycle has no valid inline ordering at all, which is the case
/// FK-lift exists for. It must produce no cross-schema edge and no complaint;
/// pgschema defers one constraint itself.
#[test]
fn same_schema_cycles_are_fine() {
    let analysis = ok(vec![file(
        "spouses.sql",
        "CREATE TABLE husband (id int PRIMARY KEY, wife_id int REFERENCES wife(id));
         CREATE TABLE wife (id int PRIMARY KEY, husband_id int REFERENCES husband(id));",
    )]);

    assert!(analysis.cycles.is_empty());
    assert_eq!(analysis.order, schemas(&["public"]));
    assert_eq!(analysis.counts.foreign_keys, 2);
}

// ---------------------------------------------------------------------------
// Determinism (spec §11.3)
// ---------------------------------------------------------------------------

#[test]
fn output_does_not_depend_on_file_order() {
    let contents = [
        (
            "z.sql",
            "CREATE TABLE zebra (id int PRIMARY KEY, a_id int REFERENCES aardvark(id));",
        ),
        ("a.sql", "CREATE TABLE aardvark (id int PRIMARY KEY);"),
        (
            "m.sql",
            "CREATE TABLE mongoose (id int PRIMARY KEY, z_id int REFERENCES zebra(id));",
        ),
    ];

    let forward = ok(contents.iter().map(|(p, c)| file(p, c)).collect());
    let reversed = ok(contents.iter().rev().map(|(p, c)| file(p, c)).collect());

    assert_eq!(forward.documents, reversed.documents);
    assert_eq!(forward.order, reversed.order);
}

#[test]
fn repeated_analysis_is_byte_identical() {
    let files = || {
        vec![file(
            "t.sql",
            "CREATE SCHEMA billing;
             CREATE TABLE billing.invoices (id int PRIMARY KEY, c int REFERENCES customers(id));
             CREATE TABLE customers (id int PRIMARY KEY);
             CREATE INDEX i ON customers (id);
             COMMENT ON TABLE customers IS 'people';",
        )]
    };

    assert_eq!(ok(files()).documents, ok(files()).documents);
}

// ---------------------------------------------------------------------------
// The statement allow-list (spec §4.3)
// ---------------------------------------------------------------------------

#[test]
fn rejects_statements_outside_the_allow_list() {
    for (sql, expected) in [
        ("CREATE VIEW v AS SELECT 1;", "CREATE VIEW"),
        ("INSERT INTO t VALUES (1);", "INSERT"),
        ("DROP TABLE t;", "DROP"),
        ("GRANT SELECT ON t TO joe;", "GRANT or REVOKE"),
        ("CREATE TYPE mood AS ENUM ('ok');", "CREATE TYPE"),
        ("CREATE SEQUENCE s;", "CREATE SEQUENCE"),
        ("ALTER TABLE t ADD COLUMN c int;", "ADD CONSTRAINT"),
        ("CREATE TABLE t (id int) INHERITS (parent);", "INHERITS"),
        ("CREATE INDEX CONCURRENTLY i ON t (c);", "CONCURRENTLY"),
    ] {
        let diagnostics = err(vec![file("bad.sql", sql)]);
        let diagnostic = only(&diagnostics, DiagnosticKind::UnsupportedStatement);
        assert!(
            diagnostic.message.contains(expected)
                || diagnostic
                    .help
                    .as_deref()
                    .is_some_and(|h| h.contains(expected)),
            "{sql:?} should mention {expected:?}, got: {diagnostic}",
        );
        assert_eq!(diagnostic.origins.len(), 1);
        assert_eq!(diagnostic.origins[0].file, "bad.sql");
    }
}

#[test]
fn reports_every_unsupported_statement_not_just_the_first() {
    let diagnostics = err(vec![
        file("a.sql", "CREATE VIEW v AS SELECT 1;"),
        file("b.sql", "INSERT INTO t VALUES (1);"),
        file("c.sql", "CREATE TABLE ok (id int);"),
    ]);

    assert_eq!(diagnostics.len(), 2);
    assert_eq!(
        diagnostics
            .iter()
            .map(|d| d.origins[0].file.as_str())
            .collect::<Vec<_>>(),
        vec!["a.sql", "b.sql"],
    );
}

#[test]
fn reports_the_line_a_bad_statement_is_on() {
    let diagnostics = err(vec![file(
        "multi.sql",
        "CREATE TABLE a (id int);\n\
         CREATE TABLE b (id int);\n\
         CREATE VIEW v AS SELECT 1;\n",
    )]);

    let diagnostic = only(&diagnostics, DiagnosticKind::UnsupportedStatement);
    assert_eq!(diagnostic.origins[0].line, 3);
}

#[test]
fn rejects_create_schema_forms_it_cannot_model() {
    for sql in [
        "CREATE SCHEMA billing CREATE TABLE accounts (id int);",
        "CREATE SCHEMA AUTHORIZATION joe;",
        "CREATE SCHEMA billing AUTHORIZATION joe;",
    ] {
        let diagnostics = err(vec![file("s.sql", sql)]);
        only(&diagnostics, DiagnosticKind::UnsupportedSchemaForm);
    }
}

#[test]
fn accepts_the_bare_create_schema_form() {
    let analysis = ok(vec![file(
        "s.sql",
        "CREATE SCHEMA billing;
         CREATE SCHEMA IF NOT EXISTS analytics;",
    )]);
    assert_eq!(analysis.managed_schemas, schemas(&["analytics", "billing"]));
}

#[test]
fn reports_a_parse_failure_with_the_file() {
    let diagnostics = err(vec![file("broken.sql", "CREATE TABLE (((;")]);
    let diagnostic = only(&diagnostics, DiagnosticKind::ParseFailure);
    assert_eq!(diagnostic.origins[0].file, "broken.sql");
}

// ---------------------------------------------------------------------------
// Source-tree validity (spec §4.5, §12.4)
// ---------------------------------------------------------------------------

#[test]
fn rejects_a_duplicate_object_naming_both_definitions() {
    let diagnostics = err(vec![
        file(
            "services/a/orders.sql",
            "CREATE TABLE orders (id int PRIMARY KEY);",
        ),
        file(
            "services/b/orders.sql",
            "CREATE TABLE orders (id int PRIMARY KEY);",
        ),
    ]);

    let diagnostic = only(&diagnostics, DiagnosticKind::DuplicateObject);
    assert!(
        diagnostic.message.contains("table public.orders"),
        "{diagnostic}"
    );
    assert_eq!(
        diagnostic
            .origins
            .iter()
            .map(|o| o.file.as_str())
            .collect::<Vec<_>>(),
        vec!["services/a/orders.sql", "services/b/orders.sql"],
        "both definitions must be named",
    );
}

#[test]
fn rejects_a_foreign_key_to_a_table_no_file_defines() {
    let diagnostics = err(vec![file(
        "orders.sql",
        "CREATE TABLE orders (id int PRIMARY KEY, customer_id int REFERENCES customers(id));",
    )]);

    let diagnostic = only(&diagnostics, DiagnosticKind::UnresolvedReference);
    assert!(
        diagnostic.message.contains("public.customers"),
        "{diagnostic}"
    );
}

/// A foreign key into a schema the tree does not describe is the common cause,
/// and the help should say so rather than implying a missing file.
#[test]
fn explains_a_foreign_key_into_an_unmanaged_schema() {
    let diagnostics = err(vec![file(
        "orders.sql",
        "CREATE TABLE orders (id int PRIMARY KEY, user_id int REFERENCES auth.users(id));",
    )]);

    let diagnostic = only(&diagnostics, DiagnosticKind::UnresolvedReference);
    let help = diagnostic.help.as_deref().unwrap_or_default();
    assert!(
        help.contains("auth"),
        "help should name the schema: {diagnostic}"
    );
}

/// Spec §12.4: verified against Postgres 18, the numeric suffix Postgres adds
/// when two constraints compete for a name follows creation order — so these
/// two could swap names between the target and pgpushy's emission order.
#[test]
fn rejects_unnamed_foreign_keys_that_would_compete_for_one_name() {
    let diagnostics = err(vec![file(
        "dual.sql",
        "CREATE TABLE t1 (id int PRIMARY KEY);
         CREATE TABLE t2 (id int PRIMARY KEY);
         CREATE TABLE dual (ref_id int REFERENCES t1(id));
         ALTER TABLE dual ADD FOREIGN KEY (ref_id) REFERENCES t2(id);",
    )]);

    let diagnostic = only(&diagnostics, DiagnosticKind::CollidingUnnamedForeignKeys);
    assert!(
        diagnostic.message.contains("public.dual(ref_id)"),
        "{diagnostic}"
    );
    assert_eq!(diagnostic.origins.len(), 2);
}

/// The check is exact: naming either constraint resolves it, and two unnamed
/// foreign keys over *different* columns never collide.
#[test]
fn allows_unnamed_foreign_keys_that_cannot_collide() {
    ok(vec![file(
        "fine.sql",
        "CREATE TABLE t1 (id int PRIMARY KEY);
         CREATE TABLE t2 (id int PRIMARY KEY);
         -- different columns: different generated names
         CREATE TABLE a (x int REFERENCES t1(id), y int REFERENCES t2(id));
         -- same column, but one is named
         CREATE TABLE b (z int REFERENCES t1(id));
         ALTER TABLE b ADD CONSTRAINT b_z_t2_fk FOREIGN KEY (z) REFERENCES t2(id);",
    )]);
}

// ---------------------------------------------------------------------------
// The managed-schema set (spec §4.4)
// ---------------------------------------------------------------------------

/// The rule that keeps pgpushy from emptying a schema it was never told about:
/// a schema with no objects is not managed, even when it is the default.
#[test]
fn the_default_schema_is_not_managed_unless_it_holds_something() {
    let analysis = ok(vec![file(
        "billing.sql",
        "CREATE SCHEMA billing; CREATE TABLE billing.invoices (id int PRIMARY KEY);",
    )]);

    assert_eq!(analysis.managed_schemas, schemas(&["billing"]));
}

#[test]
fn a_declaration_rejects_a_schema_it_omits() {
    let options = Options {
        managed_schemas: Some(schemas(&["public"])),
        ..Options::default()
    };
    let diagnostics = err_with(
        vec![
            file("public.sql", "CREATE TABLE customers (id int PRIMARY KEY);"),
            file(
                "reporting/events.sql",
                "CREATE TABLE analytics.events (id int PRIMARY KEY);",
            ),
        ],
        &options,
    );

    let diagnostic = only(&diagnostics, DiagnosticKind::SchemaNotManaged);
    assert!(diagnostic.message.contains("analytics"), "{diagnostic}");
    assert_eq!(
        diagnostic.origins[0].file, "reporting/events.sql",
        "the diagnostic must name the file that enlisted the schema",
    );
}

/// A declared schema the tree never mentions is managed with an empty desired
/// state — the only way to say "reconcile this to empty", and destructive on
/// purpose.
#[test]
fn a_declaration_can_manage_a_schema_the_tree_never_mentions() {
    let options = Options {
        managed_schemas: Some(schemas(&["public", "legacy"])),
        ..Options::default()
    };
    let analysis = ok_with(
        vec![file(
            "t.sql",
            "CREATE TABLE customers (id int PRIMARY KEY);",
        )],
        &options,
    );

    assert_eq!(analysis.managed_schemas, schemas(&["legacy", "public"]));
    // A schema with no objects still gets a document, holding just its own
    // declaration — which is what reconciles it to empty (spec §4.4).
    assert!(document(&analysis, "legacy").contains("CREATE SCHEMA IF NOT EXISTS legacy;"));
    assert_eq!(analysis.empty_schemas, schemas(&["legacy"]));
}

#[test]
fn a_non_default_default_schema_assigns_unqualified_objects() {
    let options = Options {
        default_schema: schema("app"),
        ..Options::default()
    };
    let analysis = ok_with(
        vec![file(
            "t.sql",
            "CREATE TABLE customers (id int PRIMARY KEY);",
        )],
        &options,
    );

    assert_eq!(analysis.managed_schemas, schemas(&["app"]));
    assert!(document(&analysis, "app").contains("CREATE TABLE app.customers"));
}

// ---------------------------------------------------------------------------
// Cross-schema ordering (spec §7)
// ---------------------------------------------------------------------------

#[test]
fn orders_referenced_schemas_first() {
    let analysis = ok(vec![file(
        "t.sql",
        "CREATE SCHEMA billing;
         CREATE SCHEMA reporting;
         CREATE TABLE customers (id int PRIMARY KEY);
         CREATE TABLE billing.invoices (id int PRIMARY KEY, c int REFERENCES customers(id));
         CREATE TABLE reporting.summaries (id int PRIMARY KEY, i int REFERENCES billing.invoices(id));",
    )]);

    assert!(analysis.cycles.is_empty());
    assert_eq!(analysis.order, schemas(&["public", "billing", "reporting"]));
}

/// Schemas with no cross-schema foreign keys still appear, in a stable order.
#[test]
fn independent_schemas_are_ordered_by_name() {
    let analysis = ok(vec![file(
        "t.sql",
        "CREATE SCHEMA b; CREATE SCHEMA a; CREATE SCHEMA c;
         CREATE TABLE a.t (id int); CREATE TABLE b.t (id int); CREATE TABLE c.t (id int);",
    )]);

    assert_eq!(analysis.order, schemas(&["a", "b", "c"]));
}

/// A cycle is returned as data, not an error: `plan` shows the plans anyway,
/// because those plans are what the operator needs to break it.
#[test]
fn detects_a_cross_schema_cycle_without_failing_analysis() {
    let analysis = ok(vec![file(
        "t.sql",
        "CREATE SCHEMA billing;
         CREATE TABLE customers (id int PRIMARY KEY, account_id int REFERENCES billing.accounts(id));
         CREATE TABLE billing.accounts (id int PRIMARY KEY, owner_id int REFERENCES customers(id));",
    )]);

    assert_eq!(analysis.cycles.len(), 1);
    assert_eq!(analysis.cycles[0].schemas, schemas(&["billing", "public"]));
    assert_eq!(
        analysis.order.len(),
        2,
        "every schema still appears in the order"
    );

    let diagnostic = &analysis.cycle_diagnostics()[0];
    assert_eq!(diagnostic.kind, DiagnosticKind::CrossSchemaForeignKeyCycle);
    assert!(diagnostic.message.contains("billing"), "{diagnostic}");
    assert!(diagnostic.message.contains("public"), "{diagnostic}");
    assert_eq!(
        diagnostic.origins.len(),
        2,
        "both constraints should be named"
    );
}

#[test]
fn a_three_schema_cycle_names_all_three() {
    let analysis = ok(vec![file(
        "t.sql",
        "CREATE SCHEMA b; CREATE SCHEMA c;
         CREATE TABLE a (id int PRIMARY KEY, r int REFERENCES b.b(id));
         CREATE TABLE b.b (id int PRIMARY KEY, r int REFERENCES c.c(id));
         CREATE TABLE c.c (id int PRIMARY KEY, r int REFERENCES a(id));",
    )]);

    assert_eq!(analysis.cycles.len(), 1);
    assert_eq!(analysis.cycles[0].schemas, schemas(&["b", "c", "public"]));
}

// ---------------------------------------------------------------------------
// Names inside string literals (spec §4.3)
// ---------------------------------------------------------------------------

/// pgschema cannot reach inside a literal to strip a qualifier, so pgpushy
/// must be told which schema the name is in rather than guessing.
#[test]
fn rejects_a_bare_name_inside_a_string_literal() {
    for sql in [
        "CREATE TABLE t (id int DEFAULT nextval('s'));",
        "CREATE TABLE t (id int DEFAULT nextval('s'::regclass));",
        "CREATE TABLE t (a int DEFAULT (('x'::regtype)::oid)::int);",
    ] {
        let diagnostics = err(vec![file("t.sql", sql)]);
        let diagnostic = only(&diagnostics, DiagnosticKind::UnqualifiedNameLiteral);
        let rendered = diagnostic.to_string();
        assert!(
            rendered.contains("schema"),
            "{sql}\nshould say a schema is missing, got:\n{rendered}"
        );
    }
}

/// The qualified form is what `pg_dump` writes, and it is accepted as-is.
#[test]
fn accepts_a_qualified_name_inside_a_string_literal() {
    let analysis = ok(vec![file(
        "t.sql",
        "CREATE TABLE public.t (id int DEFAULT nextval('public.s'::regclass));",
    )]);
    assert_eq!(analysis.counts.tables, 1);
}

/// A quoted identifier containing a dot is one name, not two, so it is still
/// missing its schema.
#[test]
fn a_dot_inside_quotes_does_not_count_as_a_qualifier() {
    let diagnostics = err(vec![file(
        "t.sql",
        "CREATE TABLE t (id int DEFAULT nextval('\"my.seq\"'));",
    )]);
    only(&diagnostics, DiagnosticKind::UnqualifiedNameLiteral);
}

/// An ordinary text default that happens to look like a name is data, not a
/// reference, and must not be touched.
#[test]
fn an_ordinary_string_default_is_not_a_name() {
    let analysis = ok(vec![file(
        "t.sql",
        "CREATE TABLE t (a text DEFAULT 'public.not_a_name');",
    )]);
    assert!(body(&analysis).contains("'public.not_a_name'"));
}

// ---------------------------------------------------------------------------
// Per-schema documents and the closure (spec §5.4)
// ---------------------------------------------------------------------------

fn cross_schema_tree() -> Vec<SourceFile> {
    vec![file(
        "t.sql",
        "CREATE SCHEMA billing;
         CREATE TABLE customers (id int PRIMARY KEY, email text);
         CREATE UNIQUE INDEX customers_email_ui ON customers (email);
         COMMENT ON TABLE customers IS 'one per buyer';
         CREATE TABLE regions (id int PRIMARY KEY);
         CREATE TABLE addresses (id int PRIMARY KEY, region_id int REFERENCES regions(id));
         CREATE TABLE billing.invoices (
             id int PRIMARY KEY,
             customer_email text REFERENCES customers(email)
         );
         COMMENT ON TABLE billing.invoices IS 'one per charge';",
    )]
}

/// A cross-schema foreign key drags its referent into the referencing
/// schema's document, because pgschema resolves references from the document
/// alone and never from the target.
#[test]
fn a_closure_member_appears_in_the_referencing_schemas_document() {
    let billing = document(&ok(cross_schema_tree()), "billing");
    assert!(
        billing.contains("CREATE TABLE public.customers"),
        "{billing}"
    );
    assert!(
        billing.contains("CREATE TABLE billing.invoices"),
        "{billing}"
    );
    assert!(
        billing.contains("REFERENCES public.customers (email)"),
        "{billing}"
    );
}

/// A foreign key may reference a column set whose uniqueness is backed by a
/// standalone unique index. Emitting the member's table without its indexes
/// produces a document in which the foreign key cannot be created.
#[test]
fn a_closure_member_brings_its_indexes() {
    let billing = document(&ok(cross_schema_tree()), "billing");
    assert!(
        billing.contains("CREATE UNIQUE INDEX customers_email_ui ON public.customers"),
        "the index backing the referenced column set is missing:\n{billing}"
    );
}

/// The closure stops one hop out: a member contributes no foreign keys, so
/// nothing it points at is dragged in behind it.
#[test]
fn a_closure_member_brings_neither_foreign_keys_nor_comments() {
    let tree = vec![file(
        "t.sql",
        "CREATE SCHEMA billing;
         CREATE TABLE regions (id int PRIMARY KEY);
         CREATE TABLE customers (id int PRIMARY KEY, region_id int REFERENCES regions(id));
         COMMENT ON TABLE customers IS 'one per buyer';
         CREATE TABLE billing.invoices (id int PRIMARY KEY, cid int REFERENCES customers(id));",
    )];
    let billing = document(&ok(tree), "billing");

    assert!(
        billing.contains("CREATE TABLE public.customers"),
        "{billing}"
    );
    // `public.regions` is only needed by a constraint public's document emits.
    assert!(
        !billing.contains("public.regions"),
        "the closure went a hop too far:\n{billing}"
    );
    assert!(
        !billing.contains("REFERENCES public.regions"),
        "a closure member must not bring its own foreign keys:\n{billing}"
    );
    assert!(
        !billing.contains("one per buyer"),
        "a closure member must not bring its comments:\n{billing}"
    );
}

/// Nothing flows the other way: the referenced schema's document holds only
/// its own objects, since nothing in it references the schema that points at
/// it.
#[test]
fn the_referenced_schemas_document_holds_only_its_own() {
    let public = document(&ok(cross_schema_tree()), "public");
    assert!(public.contains("CREATE TABLE public.customers"), "{public}");
    assert!(public.contains("one per buyer"), "{public}");
    assert!(
        !public.contains("billing.invoices"),
        "a schema that merely references public must not appear in it:\n{public}"
    );
    assert!(!public.contains("one per charge"), "{public}");
}

/// Each schema gets exactly one document, and a schema with no cross-schema
/// references gets no closure members at all.
#[test]
fn one_document_per_managed_schema() {
    let analysis = ok(cross_schema_tree());
    assert_eq!(
        analysis.documents.keys().cloned().collect::<Vec<_>>(),
        schemas(&["billing", "public"])
    );
    // `addresses -> regions` is same-schema, so it needs no closure and no
    // ordering edge.
    assert!(document(&analysis, "public").contains("REFERENCES public.regions (id)"));
}
